environment: ${ENVIRONMENT}
appVersion: ${APP_VERSION}

feApp:
  label: ${APP_LABEL}
  replicaCount: 1
  image:
    repo: ${APP_IMG}
    tag: ${APP_IMG_TAG}
  resources:
    requests:
      cpu: 250m
    limits:
      cpu: 500m
  port: 80

feSvc:
  label: ${APP_LABEL}
  port: 80
