apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.environment }}
  name: {{ .Values.feSvc.label }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.feSvc.port }}
  selector:
    app: {{ .Values.feSvc.label }}
